language: node_js
node_js:
  - "7"
cache:
  directories:
    - "node_modules"
script:
  - npm install jshint csslint
  - jshint autoLaunch.js noAutoLaunch.js test-connect.js webServer.js views/webClient.js
  - csslint views/style.css